<h1>Python libraries for data analysis</h1>


<li><b><span style="color:blue">Numpy</span></b>: supports numerical and array operations
<li><b><span style="color:blue">Scipy</span></b>: open source library for mathematics and scientific computing
<li><b><span style="color:blue">Pandas</span></b>: supports data manipulation and analysis
<li><b><span style="color:blue">Visualization libraries</span></b>: matplotlib, seaborne, bokeh, plotly, gmplot, and many others provide support for charts and graphs

<h1>numpy</h1>


<h2>Why numpy?</h2>
<li>Multi-dimensional arrays:
<li>Faster and more space efficient than lists 
<li>Can incorporate C/C++/Fortran code
<li>Linear algebra, Fourier transforms, Random number support



<h2>numpy array</h2>

In [36]:
import numpy as np
ax = np.array([1,2,3,4,5])
print(type(ax))
ax = np.array([[0,1,2],[3,4,5],[6,7,8]])
ax


<class 'numpy.ndarray'>


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<li>A numpy array has a data type associated with its elements
<li>and elements need to be of the same data type
<li>But an element could be an 'arbitrarily' complex object

In [2]:
np.array([1,2,'a'])

array(['1', '2', 'a'], dtype='<U11')

In [3]:
np.array([{'a':1,'b':2},4])

array([{'a': 1, 'b': 2}, 4], dtype=object)

<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

<h4>The <i>dtype</i> attribute</h4>
<li>Stores the data type in the array
<li>numpy makes a best guess of the data type

In [4]:
ax = np.array([[1,2,3,4],[5,6,7,8.3]])
ax.dtype

dtype('float64')

In [5]:
ax = np.array([{'a':1,'b':2},4])
ax.dtype

dtype('O')

In [6]:
x=['1','2','3']
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n')

[1 2 3]
[1. 2. 3.]
['1' '2' '3']


<li>The <i>astype</i> function converts from one type to another


In [7]:
ax = np.array([1,2,3,'4'])
print(ax.dtype)
ax.astype(int)

<U11


array([1, 2, 3, 4])

In [9]:
ay = ax.astype(np.float128)
print(ay)
ay.dtype

AttributeError: module 'numpy' has no attribute 'float128'

<h2>Basic operations</h2>

<h4>statistical operations</h4>

In [10]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')

97.50000000000001
19.500000000000004
3.8429155598321434


<h4>arrray arithmetic operations</h4>
<li><b>Important</b>: Arrays must be the same size!

In [11]:
x = np.array([13,24,21.2,17.6,21.7],'float')
y = np.array([1,3,4,7,2],'float')
x - y

array([12. , 21. , 17.2, 10.6, 19.7])

In [12]:
x+y

array([14. , 27. , 25.2, 24.6, 23.7])

In [13]:
x*y

array([ 13. ,  72. ,  84.8, 123.2,  43.4])

In [14]:
x/y

array([13.        ,  8.        ,  5.3       ,  2.51428571, 10.85      ])

<h2>Multi-dimensional arrays</h2>

In [15]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


<h3>Indexing</h3>

In [41]:
ax[1,3] #indexing

IndexError: index 3 is out of bounds for axis 1 with size 3

In [43]:
ax = np.arange(18).reshape(6,3)
ax

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

<h3>Slicing</h3>

In [54]:
ax[3:1,3:2]
#Intersection between ax[1:3,:] and ax[:,2:4]

array([], shape=(0, 0), dtype=int32)

<h3>Reshaping</h3>
<li>nd arrays can be reshaped as long as the total dimensionality is unchanged


In [18]:
print(ax.shape)
ax.reshape(9,2)
#ax.reshape(10,3)

(3, 6)


array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [10., 11.],
       [12., 13.],
       [14., 15.],
       [20., 21.],
       [22., 23.],
       [24., 25.]])

<h3>Creating nd arrays</h3>

<h4>Using the <i>array</i> function</h4>

In [19]:
data = [[0,1,2,3,4],[5,6,7,8,9]]
data_array = np.array(data)
data_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

<h4>Using initializers</h4>

<li>The <i>arrange</i> (array range) function


In [20]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)
ax.dtype

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


dtype('int32')

In [21]:
ax = np.arange(10)**2
print(ax)

[ 0  1  4  9 16 25 36 49 64 81]


<li>The <i>ones</i> function creates an array of 1s (floats)

In [22]:
ax = np.ones(10)
print(ax)
ax.dtype

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


dtype('float64')

In [25]:
ax = np.array([[1,2,3,4],[5,6,7,8]])
ay = np.ones_like(ax)
ay

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:

ay = np.zeros_like(ax)
ay

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

<li>The <i>identity(n)</i> function creates an identity matrix of order n

In [27]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

<li>The function <i>empty</i> creates an "empty" array
<li>Values in the array are "garbage" values

In [28]:
np.empty([2,3],float)

array([[0., 0., 0.],
       [0., 0., 0.]])

<h3>Matrix multiplication</h3>


In [29]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [30]:
np.dot(ay,ay.reshape(10,2)) #Dot product

array([[220, 265],
       [220, 265]])

<h2>Lists vs numpy arrays</h2>
<li>Lists are heterogenous. Elements of a list can be of multiple types
<li>Numpy arrays are homogeneous. Elements can be of only one type
<li>Both are mutable
<li>Homogeneity makes indexed access faster and more memory efficient
<li>numpy are optimized for matrix operations
<li>numpy provides random number support


<h3>numpy arrays are homogeneous</h3>

<h3>numpy arrays are faster</h3>

In [31]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
print(ax)
print(ay)
np.dot(ax,ay)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]
[[  0   0]
 [  1   1]
 [  4   8]
 [  9  27]
 [ 16  64]
 [ 25 125]
 [ 36 216]
 [ 49 343]
 [ 64 512]
 [ 81 729]]


array([[ 15333, 120825],
       [120825, 978405]], dtype=int32)

<h4>Functionalize this</h4>


In [32]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()
    import datetime
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    
dotproduct(10)    

datetime.timedelta(0)

<h4>Do the same with python lists</h4>


In [33]:

def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list(i) for i in zip(*ax)]
    import datetime
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(10)

datetime.timedelta(0)

<b>Digression</b> the zip function
<li>Takes two "iterables" as arguments
<li>And pairs the elements in the iterables

In [ ]:
a = [1,2,3]
b =['a','b','c']
list(zip(a,b))

<b>Digression:</b> List comprehension
<li>A mechanism for creating new lists from existing lists
<li>"Describe" the new list to generate it!
<li>Does away with for loops etc. and is a lot faster

In [ ]:
a = [1,2,3]
b = ['a','b','c']
[(a[i],b[i]) for i in range(len(a))]

In [ ]:
a = [1,2,3,4,5,6,7,8]
["Even" if val%2 == 0 else "Odd" for val in a]

<h4>Compare the two</h4>

In [ ]:
for n in [10,100,1000,10000,1000000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')

<h3>numpy indexing vs list indexing</h3>
<li>numpy arrays use direct indexing
<li>lists use chained indexing

In [ ]:
ax = np.array([1,2,3,4,8,9])
x = [1,2,3,4,8,9]

#Extract the first and last elements from the numpy array into a single array
ax[[0,-1]]

#Extract the first and last elements from the list into a new list
[x[0],x[-1]]

<h3>numpy slicing vs list slicing</h3>

In [ ]:
ax = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
ax[1:3,1:3]


In [ ]:
ax

In [ ]:
lx = [[11,12,13,14],[21,22,23,24],[31,32,33,34]]
#HELP!

<h2>batch operations on nd arrays</h2>
<li>numpy arrays allow the application of batch operations on all elements of an array
<li>without having to write a for loop or use an iterator
<li>by <i>vectorizing</i> operations, numpy is much faster than the slow for loop structure of python


<h3>batch: selecting elements using a boolean mask</h3>
<li> A boolean max applies a condition to each element in turn
<li> And returns an array of boolean with
<ul>
<li> True for each value that satisfies the condition
<li> False for every other value

In [ ]:
ax = np.array([1,4,7,9,2,3,10,11,34,2])
ax < 7

<h4>The mask can be applied as a selection operator on the array

In [ ]:
ax[ax<7]

<h4>The mask doesn't have to be constructed on the same array</h4>
<li>But the mask and the array should have the same dimensions

In [ ]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
names[bonus > 130000]


<h3>batch: arithmetic operations</h3>
<li>+, -, *, /, scalar multiplication do an element by element operation

In [ ]:
import numpy as np
ax = np.array([[1,2,3],[4,5,6]])
1/ax


<h3>batch: functional artithmetic operators</h3>

In [ ]:
ax = np.array([4,9,2,4,0,25,0])
print(np.sum(ax>5))
print(np.sum(ax[ax>5]))
print(np.count_nonzero(ax))
print(np.any(ax>10))
print(np.all(ax>0))

<h3>Logical operations with numpy</h3>
<li>logical_or
<li>logical_and

In [ ]:
np.logical_and(bonus>90000.0, bonus<400000 )

<h4>Boolean operators</h4>
<li>the numpy equivalent of "and" is "&"
<li>the numpy equivalent of "or" is "|"
<li>the numpy equivalent of "not" is "!"


In [ ]:
print(np.sum(bonus[(bonus>50000) & (bonus < 200000)]))
print(np.sum(bonus[(names=="Bill") | (names == "Qing")]))
print(np.sum(bonus[(names!="Bill")]))
print(np.sum(bonus[~((names=="Bill") | (names == "Qing"))]))


<b>Problem</b> Calculate the mean and median bonus amount for all female employees with bonus less than $100,000

In [ ]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
gender = np.array(['M','F','F','F','M'])



<b>Problem</b> Return an nd array containing the named of all female employees with bonus less than $100,000

In [ ]:
names = np.array(['Bill','Sally','Qing','Savitri','Giovanni'])
bonus = np.array([232300.56,478123.45,3891.24,98012.36,52123.50])
gender = np.array(['M','F','F','F','M'])


<h3>batch: Selecting elements using where</h3>
<li><i>where</i> function creates a new array using a conditional expression
<li>Somewhat like the if function in an excel spreadsheet

<h2>axes</h2>
<li>The axis parameter tells numpy which axis to operate along

In [ ]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ax = ax.reshape(3,4)
print(ax)

<h4>sum each column</h4>

In [ ]:
ax.sum(axis=0)

<h4>sum each row</h4>

In [ ]:
ax.sum(axis=1)

<h4>sum by depth</h4>

In [ ]:
ax=ax.reshape(2,3,2)
ax.sum(axis=2)

<h4>add an axis to an array</h4>


In [ ]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ax)
ax[:,np.newaxis]

<h4>Easy to add n-dimensions to an nd array using newaxis</h4>

In [ ]:
ax = ax.reshape(4,3)
ax[np.newaxis,np.newaxis,np.newaxis].shape

In [ ]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
np.where(ax%2==0,1,0)

<h2>Broadcasting</h2>
<li>arithmetic operations work element by element
<li>so both arrays have to be of the same length
<li><b>broadcasting</b> is used for arithmetic on arrays of different shapes

In [ ]:
ax = np.array([1,2,3])
ay = np.array([3,2,1])
ax+ay

<li>when one operand is a scalar, numpy works as if it has created a second array
<li>ax + 5 is equivalent to ax + np.array([5,5,5,])
<li>note the "as if" because it doesn't actually do that
<li>instead it <b>broadcasts</b> the 5 to each element of ax
<li>we can do this broadcasting on any dimensional array

In [ ]:
ay = np.ones([3,3])
ay

In [ ]:
ax = np.array([1,2,3])
ax + ay

<b>broadcasting</b> won't work when arrays are of incompatible dimensions

In [ ]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ay = np.array([3,4,5])
ax + ay

<h4>np.newaxis is useful here because we can convert ax into a 2D array</h4>

In [ ]:
ax[:,np.newaxis] + ay

In [ ]:
#Broadcasting effectively does this:
ax[:,np.newaxis] + np.array([[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5],[3,4,5]])

<h4>We could also convert ay into a 2D array</h4>
<li>the result will be different (why?) 

In [ ]:
ax = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ay = np.array([3,4,5])
ax + ay[:,np.newaxis]

<h2>Fancy indexing</h2>
<li>numpy let's us work on indexed subsets of an nd array
<li>this lets us construct arbitrary subsets of an nd array in any dimension

In [ ]:
ax = np.array([4,3,9,2,1,6])
ay = np.array([2,4])
ax[ay]

In [ ]:
ay = np.array([[2,4],[1,3]])
ax[ay]

<h4>multi-dimentional indexes</h4>
<li>In a 2-d, index, the index array is used to generate (row_number,col_number) pairs

In [ ]:
ax = np.array([[23,34,21,34,22],[33,44,11,29,32],[14,90,10,20,17]])
rows = np.array([0,2])
cols = np.array([1,4])
ax[rows,cols] # [ax[0,1],ax[2,4]]

<h2>Universal functions</h2>
<li>functions that perform elementwise operations on arrays
<li>fast "wrapper" functions that produce scalar (or lower dimension) results
<li>sqrt, exp, add,maximum, minimum, abs, etc.
<li>https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [ ]:
ax = np.array([1,2,3,4,5,6,7],float)
np.sqrt(ax)
np.exp(ax)

In [ ]:
ay = np.arange(10,17)
np.add(ax,ay)
np.maximum(ax,ay)

In [ ]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


In [ ]:
import scipy
scipy.nanmean(x)

<h3>Random number support in numpy</h3>

In [40]:
np.random.normal(size=10)
np.random.normal(0, 1, 100)
#np.random.exponential()
#np.random.exponential(1.0,size=(6,3))
#np.random.randint(-10,10,size=(9,9))

array([ 4.37461494e-01,  3.72013663e-03,  3.14216860e-01,  7.09363101e-01,
        6.46306116e-01,  6.86068609e-01,  2.07000367e+00,  1.64253402e+00,
        1.24702778e+00,  1.04854966e+00, -6.19036000e-01,  9.63754115e-01,
       -8.06085433e-01,  4.03695658e-01,  1.98680924e+00, -1.39132673e+00,
       -2.85559173e+00,  1.23326564e-01, -5.47485998e-01, -1.67355578e+00,
        1.29603145e+00,  3.94567299e-01, -1.98249861e-01,  1.80793879e+00,
       -2.62610061e-01, -2.36554668e-01, -1.66923116e-01, -1.37331898e-01,
       -1.18015723e+00,  1.29444889e+00,  3.16065761e-01,  4.84906575e-01,
        5.93323583e-02, -5.53579586e-01,  1.27956170e+00, -2.67387529e-01,
        9.83736616e-01, -1.17992544e+00,  1.39824531e+00,  1.22398664e+00,
       -2.00736459e-01, -2.85246146e-01,  9.60681079e-01, -1.01480411e+00,
       -4.63713983e-01, -1.76890453e-01, -7.54327297e-01, -8.31459118e-01,
        1.82288817e-01, -7.38783399e-01, -1.12403775e-01, -2.36303084e+00,
        6.00871729e-02,  